apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::015643134282:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15RII0PVTV6EQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::015643134282:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-10T03:24:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1527"
  uid: a8e43644-9067-4692-83a5-c850ea8f751c
